// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCW-8ueFz9dDy3kDEWJHmKR6de4sSyGJxE',
    appId: '1:743693754778:web:b9253a1a2d0666bea85a23',
    messagingSenderId: '743693754778',
    projectId: 'newsapp-6d56a',
    authDomain: 'newsapp-6d56a.firebaseapp.com',
    storageBucket: 'newsapp-6d56a.firebasestorage.app',
    measurementId: 'G-1JJS9KYM97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKMp4Rp-8atzqlfV_BkP9nEa1W54cDyog',
    appId: '1:743693754778:android:9cad32f5c2ace569a85a23',
    messagingSenderId: '743693754778',
    projectId: 'newsapp-6d56a',
    storageBucket: 'newsapp-6d56a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc_cmE1Z7BSbRdPVM0VHv9xlhHlowomJM',
    appId: '1:743693754778:ios:8b021c32163300d8a85a23',
    messagingSenderId: '743693754778',
    projectId: 'newsapp-6d56a',
    storageBucket: 'newsapp-6d56a.firebasestorage.app',
    iosBundleId: 'com.example.newsFlutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc_cmE1Z7BSbRdPVM0VHv9xlhHlowomJM',
    appId: '1:743693754778:ios:8b021c32163300d8a85a23',
    messagingSenderId: '743693754778',
    projectId: 'newsapp-6d56a',
    storageBucket: 'newsapp-6d56a.firebasestorage.app',
    iosBundleId: 'com.example.newsFlutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCW-8ueFz9dDy3kDEWJHmKR6de4sSyGJxE',
    appId: '1:743693754778:web:366ab5db1ea80672a85a23',
    messagingSenderId: '743693754778',
    projectId: 'newsapp-6d56a',
    authDomain: 'newsapp-6d56a.firebaseapp.com',
    storageBucket: 'newsapp-6d56a.firebasestorage.app',
    measurementId: 'G-QG4KD5MKBY',
  );
}
